spring.datasource.url=jdbc:mysql://localhost:3306/amazon_clone?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Password@21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
